# Testing setup for all models

In [1]:
import torch
import os
import numpy as np
import pandas as pd
import finetune
import importlib
from tqdm import tqdm
import matplotlib.pyplot as plt

In [2]:
importlib.reload(finetune)

<module 'finetune' from '/Users/dylan/Pycharmprojects/REDI-utwente/src/awesome_GNN/finetune.py'>

In [3]:
path_to_data = os.path.join('..', '..', 'data')
path_to_models = os.path.join(path_to_data, 'finetuned_models')

datasets = ['FGVC-Aircraft', 'StanfordCars']
model_names = ['resnet', 'densenet', 'vgg']


In [62]:
importlib.reload(finetune)
finetune.DATASET = 'FGVC-Aircraft'
finetune.CLASSIFIER_INPUT_SIZE = 244

# Get all different combinations of models
load_path = os.path.join(path_to_models, 'FGVC-Aircraft', 'resnet', 'resnet_FGVC-Aircraft_E30_occ0.pth')
save_path = os.path.join(path_to_data, 'testing_results')

finetune.safe_mkdir(save_path)

outputs, labels = finetune.test_model(load_path, save_path, _verbose=True)

dict_keys(['name', 'epochs', 'model_state_dict', 'optimizer_state_dict', 'occlusion', 'val_acc_history', 'train_acc_history', 'train_loss_history'])
name:      resnet 
epochs:    30 
occlusion: 0
0


TypeError: max() received an invalid combination of arguments - got (Tensor, dims=int), but expected one of:
 * (Tensor input)
 * (Tensor input, Tensor other, *, Tensor out)
 * (Tensor input, int dim, bool keepdim, *, tuple of Tensors out)
 * (Tensor input, name dim, bool keepdim, *, tuple of Tensors out)


In [18]:
_, preds = torch.max(outputs, dim=1)
print(preds.numpy())


[55 56 67 99 95  4 24 38]
tensor([ 5.1513,  3.8392,  6.9846,  6.3211,  7.2716,  6.3959, -0.1225,  7.0540],
       grad_fn=<MaxBackward0>)


In [59]:
from sklearn.metrics import precision_score, recall_score, f1_score

In [60]:
def precision(outputs, labels):
    op = outputs
    la = labels
    _, preds = torch.max(op, dim=1)
    return torch.tensor(precision_score(la, preds, average='weighted', zero_division=0)).item()

def recall(outputs, labels):
    op = outputs
    la = labels
    _, preds = torch.max(op, dim=1)
    return torch.tensor(recall_score(la, preds, average='weighted', zero_division=0)).item()

def f1(outputs, labels):
    op = outputs
    la = labels
    _, preds = torch.max(op, dim=1)
    return torch.tensor(f1_score(la, preds, average='weighted', zero_division=0)).item()

In [61]:
print(f'precision : {precision(outputs, labels)}')
print(f'recall : {recall(outputs, labels)}')
print(f'f1 : {f1(outputs, labels)}')

precision : 0.25
recall : 0.125
f1 : 0.16666666666666666


ValueError: Samplewise metrics are not available outside of multilabel classification.

[12 21 13 28 26  4  4  6]
